<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="msp" nsURI="msp" nsPrefix="msp">
  <eClassifiers xsi:type="ecore:EClass" name="Unité" instanceTypeName="Unite">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unites" eType="#//Unité"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classification" instanceTypeName="Classification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifications" eType="#//Classification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conservation" instanceTypeName="Conservation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unite" eType="#//Unité"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regles" eType="#//Règle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Règle" instanceTypeName="Regle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actif" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="12"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semiactif" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="12"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inactif" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="12"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exemplaire" eType="#//exemplaire"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="statut">
    <eLiterals name="actif" value="1"/>
    <eLiterals name="semiactif" value="2" literal="semi-actif"/>
    <eLiterals name="inactif" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="exemplaire">
    <eLiterals name="principal"/>
    <eLiterals name="secondaire"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Calendrier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regles" eType="#//Conservation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plan"/>
  <eClassifiers xsi:type="ecore:EClass" name="Organisation"/>
</ecore:EPackage>
